---
abstract: 'A simple, unified interface for Textile, Markdown and BBCode.'
author:
  - 'Ido Perlmuter, C<< <ido at fc-bnei-yehuda.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Markup-Unified
no_index:
  directory:
    - inc
    - t
requires:
  HTML::BBCode: 2.06
  Moose: 0
  Text::Markdown: 1.0.25
  Text::Textile: 2.12
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
