---
abstract: 'A simple, unified interface for Textile, Markdown and BBCode.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Markup-Unified
requires:
  Module::Load::Conditional: 0
  overload: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/ido50/Markup-Unified
  repository: https://github.com/ido50/Markup-Unified.git
version: 0.04
